package com.entity.erpStock;

public class WlbStockAllocationWithBLOBs extends WlbStockAllocation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.ims_request_str
     *
     * @mbg.generated
     */
    private String imsRequestStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.ims_response_str
     *
     * @mbg.generated
     */
    private String imsResponseStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.ims_request_str
     *
     * @return the value of wlb_stock_allocation.ims_request_str
     *
     * @mbg.generated
     */
    public String getImsRequestStr() {
        return imsRequestStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.ims_request_str
     *
     * @param imsRequestStr the value for wlb_stock_allocation.ims_request_str
     *
     * @mbg.generated
     */
    public void setImsRequestStr(String imsRequestStr) {
        this.imsRequestStr = imsRequestStr == null ? null : imsRequestStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.ims_response_str
     *
     * @return the value of wlb_stock_allocation.ims_response_str
     *
     * @mbg.generated
     */
    public String getImsResponseStr() {
        return imsResponseStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.ims_response_str
     *
     * @param imsResponseStr the value for wlb_stock_allocation.ims_response_str
     *
     * @mbg.generated
     */
    public void setImsResponseStr(String imsResponseStr) {
        this.imsResponseStr = imsResponseStr == null ? null : imsResponseStr.trim();
    }
}