package com.entity.erpStock;

import java.util.Date;

public class WlbStockAllocation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.order_type_id
     *
     * @mbg.generated
     */
    private Long orderTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.allocation_order_code
     *
     * @mbg.generated
     */
    private String allocationOrderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.allocation_order_source_code
     *
     * @mbg.generated
     */
    private String allocationOrderSourceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.out_order_status
     *
     * @mbg.generated
     */
    private String outOrderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.out_order_code
     *
     * @mbg.generated
     */
    private String outOrderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.out_order_source_code
     *
     * @mbg.generated
     */
    private String outOrderSourceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.out_store_code
     *
     * @mbg.generated
     */
    private String outStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.out_warehouse_id
     *
     * @mbg.generated
     */
    private Long outWarehouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.out_warehouse_code
     *
     * @mbg.generated
     */
    private String outWarehouseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.out_store_name
     *
     * @mbg.generated
     */
    private String outStoreName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.out_quantity
     *
     * @mbg.generated
     */
    private Integer outQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.out_real_time
     *
     * @mbg.generated
     */
    private Date outRealTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.in_order_status
     *
     * @mbg.generated
     */
    private String inOrderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.in_order_code
     *
     * @mbg.generated
     */
    private String inOrderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.in_order_source_code
     *
     * @mbg.generated
     */
    private String inOrderSourceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.in_store_code
     *
     * @mbg.generated
     */
    private String inStoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.in_warehouse_id
     *
     * @mbg.generated
     */
    private Long inWarehouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.in_warehouse_code
     *
     * @mbg.generated
     */
    private String inWarehouseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.in_store_name
     *
     * @mbg.generated
     */
    private String inStoreName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.in_quantity
     *
     * @mbg.generated
     */
    private Integer inQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.in_real_time
     *
     * @mbg.generated
     */
    private Date inRealTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.create_name
     *
     * @mbg.generated
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.approve
     *
     * @mbg.generated
     */
    private Boolean approve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.check_name
     *
     * @mbg.generated
     */
    private String checkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.check_date
     *
     * @mbg.generated
     */
    private Date checkDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.cancel
     *
     * @mbg.generated
     */
    private Boolean cancel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.cancel_name
     *
     * @mbg.generated
     */
    private String cancelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.cancel_date
     *
     * @mbg.generated
     */
    private Date cancelDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.is_error
     *
     * @mbg.generated
     */
    private Integer isError;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.error_message
     *
     * @mbg.generated
     */
    private String errorMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.modified
     *
     * @mbg.generated
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.user_nick
     *
     * @mbg.generated
     */
    private String userNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.buyer_nick
     *
     * @mbg.generated
     */
    private String buyerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.order_sub_type
     *
     * @mbg.generated
     */
    private String orderSubType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.is_sendIMS
     *
     * @mbg.generated
     */
    private Boolean isSendims;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.ims_push_sign
     *
     * @mbg.generated
     */
    private Integer imsPushSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.ims_push_msg
     *
     * @mbg.generated
     */
    private String imsPushMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.ims_push_time
     *
     * @mbg.generated
     */
    private Date imsPushTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.pcode
     *
     * @mbg.generated
     */
    private String pcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.pid
     *
     * @mbg.generated
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlb_stock_allocation.ims_db_code
     *
     * @mbg.generated
     */
    private String imsDbCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.id
     *
     * @return the value of wlb_stock_allocation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.id
     *
     * @param id the value for wlb_stock_allocation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.order_type_id
     *
     * @return the value of wlb_stock_allocation.order_type_id
     *
     * @mbg.generated
     */
    public Long getOrderTypeId() {
        return orderTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.order_type_id
     *
     * @param orderTypeId the value for wlb_stock_allocation.order_type_id
     *
     * @mbg.generated
     */
    public void setOrderTypeId(Long orderTypeId) {
        this.orderTypeId = orderTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.allocation_order_code
     *
     * @return the value of wlb_stock_allocation.allocation_order_code
     *
     * @mbg.generated
     */
    public String getAllocationOrderCode() {
        return allocationOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.allocation_order_code
     *
     * @param allocationOrderCode the value for wlb_stock_allocation.allocation_order_code
     *
     * @mbg.generated
     */
    public void setAllocationOrderCode(String allocationOrderCode) {
        this.allocationOrderCode = allocationOrderCode == null ? null : allocationOrderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.allocation_order_source_code
     *
     * @return the value of wlb_stock_allocation.allocation_order_source_code
     *
     * @mbg.generated
     */
    public String getAllocationOrderSourceCode() {
        return allocationOrderSourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.allocation_order_source_code
     *
     * @param allocationOrderSourceCode the value for wlb_stock_allocation.allocation_order_source_code
     *
     * @mbg.generated
     */
    public void setAllocationOrderSourceCode(String allocationOrderSourceCode) {
        this.allocationOrderSourceCode = allocationOrderSourceCode == null ? null : allocationOrderSourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.out_order_status
     *
     * @return the value of wlb_stock_allocation.out_order_status
     *
     * @mbg.generated
     */
    public String getOutOrderStatus() {
        return outOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.out_order_status
     *
     * @param outOrderStatus the value for wlb_stock_allocation.out_order_status
     *
     * @mbg.generated
     */
    public void setOutOrderStatus(String outOrderStatus) {
        this.outOrderStatus = outOrderStatus == null ? null : outOrderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.out_order_code
     *
     * @return the value of wlb_stock_allocation.out_order_code
     *
     * @mbg.generated
     */
    public String getOutOrderCode() {
        return outOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.out_order_code
     *
     * @param outOrderCode the value for wlb_stock_allocation.out_order_code
     *
     * @mbg.generated
     */
    public void setOutOrderCode(String outOrderCode) {
        this.outOrderCode = outOrderCode == null ? null : outOrderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.out_order_source_code
     *
     * @return the value of wlb_stock_allocation.out_order_source_code
     *
     * @mbg.generated
     */
    public String getOutOrderSourceCode() {
        return outOrderSourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.out_order_source_code
     *
     * @param outOrderSourceCode the value for wlb_stock_allocation.out_order_source_code
     *
     * @mbg.generated
     */
    public void setOutOrderSourceCode(String outOrderSourceCode) {
        this.outOrderSourceCode = outOrderSourceCode == null ? null : outOrderSourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.out_store_code
     *
     * @return the value of wlb_stock_allocation.out_store_code
     *
     * @mbg.generated
     */
    public String getOutStoreCode() {
        return outStoreCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.out_store_code
     *
     * @param outStoreCode the value for wlb_stock_allocation.out_store_code
     *
     * @mbg.generated
     */
    public void setOutStoreCode(String outStoreCode) {
        this.outStoreCode = outStoreCode == null ? null : outStoreCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.out_warehouse_id
     *
     * @return the value of wlb_stock_allocation.out_warehouse_id
     *
     * @mbg.generated
     */
    public Long getOutWarehouseId() {
        return outWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.out_warehouse_id
     *
     * @param outWarehouseId the value for wlb_stock_allocation.out_warehouse_id
     *
     * @mbg.generated
     */
    public void setOutWarehouseId(Long outWarehouseId) {
        this.outWarehouseId = outWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.out_warehouse_code
     *
     * @return the value of wlb_stock_allocation.out_warehouse_code
     *
     * @mbg.generated
     */
    public String getOutWarehouseCode() {
        return outWarehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.out_warehouse_code
     *
     * @param outWarehouseCode the value for wlb_stock_allocation.out_warehouse_code
     *
     * @mbg.generated
     */
    public void setOutWarehouseCode(String outWarehouseCode) {
        this.outWarehouseCode = outWarehouseCode == null ? null : outWarehouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.out_store_name
     *
     * @return the value of wlb_stock_allocation.out_store_name
     *
     * @mbg.generated
     */
    public String getOutStoreName() {
        return outStoreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.out_store_name
     *
     * @param outStoreName the value for wlb_stock_allocation.out_store_name
     *
     * @mbg.generated
     */
    public void setOutStoreName(String outStoreName) {
        this.outStoreName = outStoreName == null ? null : outStoreName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.out_quantity
     *
     * @return the value of wlb_stock_allocation.out_quantity
     *
     * @mbg.generated
     */
    public Integer getOutQuantity() {
        return outQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.out_quantity
     *
     * @param outQuantity the value for wlb_stock_allocation.out_quantity
     *
     * @mbg.generated
     */
    public void setOutQuantity(Integer outQuantity) {
        this.outQuantity = outQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.out_real_time
     *
     * @return the value of wlb_stock_allocation.out_real_time
     *
     * @mbg.generated
     */
    public Date getOutRealTime() {
        return outRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.out_real_time
     *
     * @param outRealTime the value for wlb_stock_allocation.out_real_time
     *
     * @mbg.generated
     */
    public void setOutRealTime(Date outRealTime) {
        this.outRealTime = outRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.in_order_status
     *
     * @return the value of wlb_stock_allocation.in_order_status
     *
     * @mbg.generated
     */
    public String getInOrderStatus() {
        return inOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.in_order_status
     *
     * @param inOrderStatus the value for wlb_stock_allocation.in_order_status
     *
     * @mbg.generated
     */
    public void setInOrderStatus(String inOrderStatus) {
        this.inOrderStatus = inOrderStatus == null ? null : inOrderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.in_order_code
     *
     * @return the value of wlb_stock_allocation.in_order_code
     *
     * @mbg.generated
     */
    public String getInOrderCode() {
        return inOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.in_order_code
     *
     * @param inOrderCode the value for wlb_stock_allocation.in_order_code
     *
     * @mbg.generated
     */
    public void setInOrderCode(String inOrderCode) {
        this.inOrderCode = inOrderCode == null ? null : inOrderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.in_order_source_code
     *
     * @return the value of wlb_stock_allocation.in_order_source_code
     *
     * @mbg.generated
     */
    public String getInOrderSourceCode() {
        return inOrderSourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.in_order_source_code
     *
     * @param inOrderSourceCode the value for wlb_stock_allocation.in_order_source_code
     *
     * @mbg.generated
     */
    public void setInOrderSourceCode(String inOrderSourceCode) {
        this.inOrderSourceCode = inOrderSourceCode == null ? null : inOrderSourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.in_store_code
     *
     * @return the value of wlb_stock_allocation.in_store_code
     *
     * @mbg.generated
     */
    public String getInStoreCode() {
        return inStoreCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.in_store_code
     *
     * @param inStoreCode the value for wlb_stock_allocation.in_store_code
     *
     * @mbg.generated
     */
    public void setInStoreCode(String inStoreCode) {
        this.inStoreCode = inStoreCode == null ? null : inStoreCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.in_warehouse_id
     *
     * @return the value of wlb_stock_allocation.in_warehouse_id
     *
     * @mbg.generated
     */
    public Long getInWarehouseId() {
        return inWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.in_warehouse_id
     *
     * @param inWarehouseId the value for wlb_stock_allocation.in_warehouse_id
     *
     * @mbg.generated
     */
    public void setInWarehouseId(Long inWarehouseId) {
        this.inWarehouseId = inWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.in_warehouse_code
     *
     * @return the value of wlb_stock_allocation.in_warehouse_code
     *
     * @mbg.generated
     */
    public String getInWarehouseCode() {
        return inWarehouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.in_warehouse_code
     *
     * @param inWarehouseCode the value for wlb_stock_allocation.in_warehouse_code
     *
     * @mbg.generated
     */
    public void setInWarehouseCode(String inWarehouseCode) {
        this.inWarehouseCode = inWarehouseCode == null ? null : inWarehouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.in_store_name
     *
     * @return the value of wlb_stock_allocation.in_store_name
     *
     * @mbg.generated
     */
    public String getInStoreName() {
        return inStoreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.in_store_name
     *
     * @param inStoreName the value for wlb_stock_allocation.in_store_name
     *
     * @mbg.generated
     */
    public void setInStoreName(String inStoreName) {
        this.inStoreName = inStoreName == null ? null : inStoreName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.in_quantity
     *
     * @return the value of wlb_stock_allocation.in_quantity
     *
     * @mbg.generated
     */
    public Integer getInQuantity() {
        return inQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.in_quantity
     *
     * @param inQuantity the value for wlb_stock_allocation.in_quantity
     *
     * @mbg.generated
     */
    public void setInQuantity(Integer inQuantity) {
        this.inQuantity = inQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.in_real_time
     *
     * @return the value of wlb_stock_allocation.in_real_time
     *
     * @mbg.generated
     */
    public Date getInRealTime() {
        return inRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.in_real_time
     *
     * @param inRealTime the value for wlb_stock_allocation.in_real_time
     *
     * @mbg.generated
     */
    public void setInRealTime(Date inRealTime) {
        this.inRealTime = inRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.create_name
     *
     * @return the value of wlb_stock_allocation.create_name
     *
     * @mbg.generated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.create_name
     *
     * @param createName the value for wlb_stock_allocation.create_name
     *
     * @mbg.generated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.approve
     *
     * @return the value of wlb_stock_allocation.approve
     *
     * @mbg.generated
     */
    public Boolean getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.approve
     *
     * @param approve the value for wlb_stock_allocation.approve
     *
     * @mbg.generated
     */
    public void setApprove(Boolean approve) {
        this.approve = approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.check_name
     *
     * @return the value of wlb_stock_allocation.check_name
     *
     * @mbg.generated
     */
    public String getCheckName() {
        return checkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.check_name
     *
     * @param checkName the value for wlb_stock_allocation.check_name
     *
     * @mbg.generated
     */
    public void setCheckName(String checkName) {
        this.checkName = checkName == null ? null : checkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.check_date
     *
     * @return the value of wlb_stock_allocation.check_date
     *
     * @mbg.generated
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.check_date
     *
     * @param checkDate the value for wlb_stock_allocation.check_date
     *
     * @mbg.generated
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.cancel
     *
     * @return the value of wlb_stock_allocation.cancel
     *
     * @mbg.generated
     */
    public Boolean getCancel() {
        return cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.cancel
     *
     * @param cancel the value for wlb_stock_allocation.cancel
     *
     * @mbg.generated
     */
    public void setCancel(Boolean cancel) {
        this.cancel = cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.cancel_name
     *
     * @return the value of wlb_stock_allocation.cancel_name
     *
     * @mbg.generated
     */
    public String getCancelName() {
        return cancelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.cancel_name
     *
     * @param cancelName the value for wlb_stock_allocation.cancel_name
     *
     * @mbg.generated
     */
    public void setCancelName(String cancelName) {
        this.cancelName = cancelName == null ? null : cancelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.cancel_date
     *
     * @return the value of wlb_stock_allocation.cancel_date
     *
     * @mbg.generated
     */
    public Date getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.cancel_date
     *
     * @param cancelDate the value for wlb_stock_allocation.cancel_date
     *
     * @mbg.generated
     */
    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.remark
     *
     * @return the value of wlb_stock_allocation.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.remark
     *
     * @param remark the value for wlb_stock_allocation.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.is_error
     *
     * @return the value of wlb_stock_allocation.is_error
     *
     * @mbg.generated
     */
    public Integer getIsError() {
        return isError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.is_error
     *
     * @param isError the value for wlb_stock_allocation.is_error
     *
     * @mbg.generated
     */
    public void setIsError(Integer isError) {
        this.isError = isError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.error_message
     *
     * @return the value of wlb_stock_allocation.error_message
     *
     * @mbg.generated
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.error_message
     *
     * @param errorMessage the value for wlb_stock_allocation.error_message
     *
     * @mbg.generated
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage == null ? null : errorMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.create_time
     *
     * @return the value of wlb_stock_allocation.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.create_time
     *
     * @param createTime the value for wlb_stock_allocation.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.created
     *
     * @return the value of wlb_stock_allocation.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.created
     *
     * @param created the value for wlb_stock_allocation.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.modified
     *
     * @return the value of wlb_stock_allocation.modified
     *
     * @mbg.generated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.modified
     *
     * @param modified the value for wlb_stock_allocation.modified
     *
     * @mbg.generated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.tenant_id
     *
     * @return the value of wlb_stock_allocation.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.tenant_id
     *
     * @param tenantId the value for wlb_stock_allocation.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.code
     *
     * @return the value of wlb_stock_allocation.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.code
     *
     * @param code the value for wlb_stock_allocation.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.user_id
     *
     * @return the value of wlb_stock_allocation.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.user_id
     *
     * @param userId the value for wlb_stock_allocation.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.user_nick
     *
     * @return the value of wlb_stock_allocation.user_nick
     *
     * @mbg.generated
     */
    public String getUserNick() {
        return userNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.user_nick
     *
     * @param userNick the value for wlb_stock_allocation.user_nick
     *
     * @mbg.generated
     */
    public void setUserNick(String userNick) {
        this.userNick = userNick == null ? null : userNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.buyer_nick
     *
     * @return the value of wlb_stock_allocation.buyer_nick
     *
     * @mbg.generated
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.buyer_nick
     *
     * @param buyerNick the value for wlb_stock_allocation.buyer_nick
     *
     * @mbg.generated
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.order_sub_type
     *
     * @return the value of wlb_stock_allocation.order_sub_type
     *
     * @mbg.generated
     */
    public String getOrderSubType() {
        return orderSubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.order_sub_type
     *
     * @param orderSubType the value for wlb_stock_allocation.order_sub_type
     *
     * @mbg.generated
     */
    public void setOrderSubType(String orderSubType) {
        this.orderSubType = orderSubType == null ? null : orderSubType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.order_type
     *
     * @return the value of wlb_stock_allocation.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.order_type
     *
     * @param orderType the value for wlb_stock_allocation.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.is_sendIMS
     *
     * @return the value of wlb_stock_allocation.is_sendIMS
     *
     * @mbg.generated
     */
    public Boolean getIsSendims() {
        return isSendims;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.is_sendIMS
     *
     * @param isSendims the value for wlb_stock_allocation.is_sendIMS
     *
     * @mbg.generated
     */
    public void setIsSendims(Boolean isSendims) {
        this.isSendims = isSendims;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.ims_push_sign
     *
     * @return the value of wlb_stock_allocation.ims_push_sign
     *
     * @mbg.generated
     */
    public Integer getImsPushSign() {
        return imsPushSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.ims_push_sign
     *
     * @param imsPushSign the value for wlb_stock_allocation.ims_push_sign
     *
     * @mbg.generated
     */
    public void setImsPushSign(Integer imsPushSign) {
        this.imsPushSign = imsPushSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.ims_push_msg
     *
     * @return the value of wlb_stock_allocation.ims_push_msg
     *
     * @mbg.generated
     */
    public String getImsPushMsg() {
        return imsPushMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.ims_push_msg
     *
     * @param imsPushMsg the value for wlb_stock_allocation.ims_push_msg
     *
     * @mbg.generated
     */
    public void setImsPushMsg(String imsPushMsg) {
        this.imsPushMsg = imsPushMsg == null ? null : imsPushMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.ims_push_time
     *
     * @return the value of wlb_stock_allocation.ims_push_time
     *
     * @mbg.generated
     */
    public Date getImsPushTime() {
        return imsPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.ims_push_time
     *
     * @param imsPushTime the value for wlb_stock_allocation.ims_push_time
     *
     * @mbg.generated
     */
    public void setImsPushTime(Date imsPushTime) {
        this.imsPushTime = imsPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.pcode
     *
     * @return the value of wlb_stock_allocation.pcode
     *
     * @mbg.generated
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.pcode
     *
     * @param pcode the value for wlb_stock_allocation.pcode
     *
     * @mbg.generated
     */
    public void setPcode(String pcode) {
        this.pcode = pcode == null ? null : pcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.pid
     *
     * @return the value of wlb_stock_allocation.pid
     *
     * @mbg.generated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.pid
     *
     * @param pid the value for wlb_stock_allocation.pid
     *
     * @mbg.generated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlb_stock_allocation.ims_db_code
     *
     * @return the value of wlb_stock_allocation.ims_db_code
     *
     * @mbg.generated
     */
    public String getImsDbCode() {
        return imsDbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlb_stock_allocation.ims_db_code
     *
     * @param imsDbCode the value for wlb_stock_allocation.ims_db_code
     *
     * @mbg.generated
     */
    public void setImsDbCode(String imsDbCode) {
        this.imsDbCode = imsDbCode == null ? null : imsDbCode.trim();
    }
}