package com.entity.erpreport;

import java.math.BigDecimal;
import java.util.Date;

public class AlipayAccountOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.modified
     *
     * @mbg.generated
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.tenant_id
     *
     * @mbg.generated
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.pay_type
     *
     * @mbg.generated
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.business_type
     *
     * @mbg.generated
     */
    private String businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.balance
     *
     * @mbg.generated
     */
    private String balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.in_amount
     *
     * @mbg.generated
     */
    private BigDecimal inAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.out_amount
     *
     * @mbg.generated
     */
    private BigDecimal outAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.alipay_order_no
     *
     * @mbg.generated
     */
    private String alipayOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.merchant_order_no
     *
     * @mbg.generated
     */
    private String merchantOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.self_user_id
     *
     * @mbg.generated
     */
    private String selfUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.opt_user_id
     *
     * @mbg.generated
     */
    private String optUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.seller_Nick
     *
     * @mbg.generated
     */
    private String sellerNick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.first_sys_id
     *
     * @mbg.generated
     */
    private Long firstSysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.first_sys_name
     *
     * @mbg.generated
     */
    private String firstSysName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.second_sys_id
     *
     * @mbg.generated
     */
    private Long secondSysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.second_sys_name
     *
     * @mbg.generated
     */
    private String secondSysName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.platForm_No
     *
     * @mbg.generated
     */
    private String platformNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.new_sys_subject_id
     *
     * @mbg.generated
     */
    private Long newSysSubjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.new_Sys_Subject_Name
     *
     * @mbg.generated
     */
    private String newSysSubjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.new_Type
     *
     * @mbg.generated
     */
    private Integer newType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.is_Sign
     *
     * @mbg.generated
     */
    private Integer isSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.sign_Time
     *
     * @mbg.generated
     */
    private Date signTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.new_platform_subject_id
     *
     * @mbg.generated
     */
    private Long newPlatformSubjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.new_Platform_Subject_Name
     *
     * @mbg.generated
     */
    private String newPlatformSubjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.is_Exception
     *
     * @mbg.generated
     */
    private Integer isException;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.return_id
     *
     * @mbg.generated
     */
    private String returnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.exception_Msg
     *
     * @mbg.generated
     */
    private String exceptionMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.fenxiao_id
     *
     * @mbg.generated
     */
    private Long fenxiaoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.debtor_Code
     *
     * @mbg.generated
     */
    private String debtorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.debtor_Subject
     *
     * @mbg.generated
     */
    private String debtorSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.debtor_XNEGP
     *
     * @mbg.generated
     */
    private String debtorXnegp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.debtor_Acc_Type
     *
     * @mbg.generated
     */
    private String debtorAccType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.debtor_Cash_Flow_Code
     *
     * @mbg.generated
     */
    private String debtorCashFlowCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.credit_Code
     *
     * @mbg.generated
     */
    private String creditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.credit_Subject
     *
     * @mbg.generated
     */
    private String creditSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.credit_XNEGP
     *
     * @mbg.generated
     */
    private String creditXnegp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.credit_Acc_Type
     *
     * @mbg.generated
     */
    private String creditAccType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.credit_Cash_Flow_Code
     *
     * @mbg.generated
     */
    private String creditCashFlowCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.is_reconciled
     *
     * @mbg.generated
     */
    private Boolean isReconciled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.reconcile_time
     *
     * @mbg.generated
     */
    private Date reconcileTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.ims_Push_Msg
     *
     * @mbg.generated
     */
    private String imsPushMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.ims_Push_Time
     *
     * @mbg.generated
     */
    private Date imsPushTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.cancel
     *
     * @mbg.generated
     */
    private Boolean cancel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.cancel_operator
     *
     * @mbg.generated
     */
    private String cancelOperator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.cancel_date
     *
     * @mbg.generated
     */
    private Date cancelDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.subject_convert
     *
     * @mbg.generated
     */
    private Integer subjectConvert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.plus_or_minus
     *
     * @mbg.generated
     */
    private Integer plusOrMinus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.test_field
     *
     * @mbg.generated
     */
    private String testField;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.sapcolsechangtime
     *
     * @mbg.generated
     */
    private Date sapcolsechangtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.is_hz
     *
     * @mbg.generated
     */
    private Integer isHz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_account_order.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.id
     *
     * @return the value of alipay_account_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.id
     *
     * @param id the value for alipay_account_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.created
     *
     * @return the value of alipay_account_order.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.created
     *
     * @param created the value for alipay_account_order.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.modified
     *
     * @return the value of alipay_account_order.modified
     *
     * @mbg.generated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.modified
     *
     * @param modified the value for alipay_account_order.modified
     *
     * @mbg.generated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.version
     *
     * @return the value of alipay_account_order.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.version
     *
     * @param version the value for alipay_account_order.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.tenant_id
     *
     * @return the value of alipay_account_order.tenant_id
     *
     * @mbg.generated
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.tenant_id
     *
     * @param tenantId the value for alipay_account_order.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.create_time
     *
     * @return the value of alipay_account_order.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.create_time
     *
     * @param createTime the value for alipay_account_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.pay_type
     *
     * @return the value of alipay_account_order.pay_type
     *
     * @mbg.generated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.pay_type
     *
     * @param payType the value for alipay_account_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.type
     *
     * @return the value of alipay_account_order.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.type
     *
     * @param type the value for alipay_account_order.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.business_type
     *
     * @return the value of alipay_account_order.business_type
     *
     * @mbg.generated
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.business_type
     *
     * @param businessType the value for alipay_account_order.business_type
     *
     * @mbg.generated
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.balance
     *
     * @return the value of alipay_account_order.balance
     *
     * @mbg.generated
     */
    public String getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.balance
     *
     * @param balance the value for alipay_account_order.balance
     *
     * @mbg.generated
     */
    public void setBalance(String balance) {
        this.balance = balance == null ? null : balance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.in_amount
     *
     * @return the value of alipay_account_order.in_amount
     *
     * @mbg.generated
     */
    public BigDecimal getInAmount() {
        return inAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.in_amount
     *
     * @param inAmount the value for alipay_account_order.in_amount
     *
     * @mbg.generated
     */
    public void setInAmount(BigDecimal inAmount) {
        this.inAmount = inAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.out_amount
     *
     * @return the value of alipay_account_order.out_amount
     *
     * @mbg.generated
     */
    public BigDecimal getOutAmount() {
        return outAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.out_amount
     *
     * @param outAmount the value for alipay_account_order.out_amount
     *
     * @mbg.generated
     */
    public void setOutAmount(BigDecimal outAmount) {
        this.outAmount = outAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.alipay_order_no
     *
     * @return the value of alipay_account_order.alipay_order_no
     *
     * @mbg.generated
     */
    public String getAlipayOrderNo() {
        return alipayOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.alipay_order_no
     *
     * @param alipayOrderNo the value for alipay_account_order.alipay_order_no
     *
     * @mbg.generated
     */
    public void setAlipayOrderNo(String alipayOrderNo) {
        this.alipayOrderNo = alipayOrderNo == null ? null : alipayOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.merchant_order_no
     *
     * @return the value of alipay_account_order.merchant_order_no
     *
     * @mbg.generated
     */
    public String getMerchantOrderNo() {
        return merchantOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.merchant_order_no
     *
     * @param merchantOrderNo the value for alipay_account_order.merchant_order_no
     *
     * @mbg.generated
     */
    public void setMerchantOrderNo(String merchantOrderNo) {
        this.merchantOrderNo = merchantOrderNo == null ? null : merchantOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.self_user_id
     *
     * @return the value of alipay_account_order.self_user_id
     *
     * @mbg.generated
     */
    public String getSelfUserId() {
        return selfUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.self_user_id
     *
     * @param selfUserId the value for alipay_account_order.self_user_id
     *
     * @mbg.generated
     */
    public void setSelfUserId(String selfUserId) {
        this.selfUserId = selfUserId == null ? null : selfUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.opt_user_id
     *
     * @return the value of alipay_account_order.opt_user_id
     *
     * @mbg.generated
     */
    public String getOptUserId() {
        return optUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.opt_user_id
     *
     * @param optUserId the value for alipay_account_order.opt_user_id
     *
     * @mbg.generated
     */
    public void setOptUserId(String optUserId) {
        this.optUserId = optUserId == null ? null : optUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.sign
     *
     * @return the value of alipay_account_order.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.sign
     *
     * @param sign the value for alipay_account_order.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.seller_Nick
     *
     * @return the value of alipay_account_order.seller_Nick
     *
     * @mbg.generated
     */
    public String getSellerNick() {
        return sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.seller_Nick
     *
     * @param sellerNick the value for alipay_account_order.seller_Nick
     *
     * @mbg.generated
     */
    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick == null ? null : sellerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.shop_id
     *
     * @return the value of alipay_account_order.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.shop_id
     *
     * @param shopId the value for alipay_account_order.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.first_sys_id
     *
     * @return the value of alipay_account_order.first_sys_id
     *
     * @mbg.generated
     */
    public Long getFirstSysId() {
        return firstSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.first_sys_id
     *
     * @param firstSysId the value for alipay_account_order.first_sys_id
     *
     * @mbg.generated
     */
    public void setFirstSysId(Long firstSysId) {
        this.firstSysId = firstSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.first_sys_name
     *
     * @return the value of alipay_account_order.first_sys_name
     *
     * @mbg.generated
     */
    public String getFirstSysName() {
        return firstSysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.first_sys_name
     *
     * @param firstSysName the value for alipay_account_order.first_sys_name
     *
     * @mbg.generated
     */
    public void setFirstSysName(String firstSysName) {
        this.firstSysName = firstSysName == null ? null : firstSysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.second_sys_id
     *
     * @return the value of alipay_account_order.second_sys_id
     *
     * @mbg.generated
     */
    public Long getSecondSysId() {
        return secondSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.second_sys_id
     *
     * @param secondSysId the value for alipay_account_order.second_sys_id
     *
     * @mbg.generated
     */
    public void setSecondSysId(Long secondSysId) {
        this.secondSysId = secondSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.second_sys_name
     *
     * @return the value of alipay_account_order.second_sys_name
     *
     * @mbg.generated
     */
    public String getSecondSysName() {
        return secondSysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.second_sys_name
     *
     * @param secondSysName the value for alipay_account_order.second_sys_name
     *
     * @mbg.generated
     */
    public void setSecondSysName(String secondSysName) {
        this.secondSysName = secondSysName == null ? null : secondSysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.platForm_No
     *
     * @return the value of alipay_account_order.platForm_No
     *
     * @mbg.generated
     */
    public String getPlatformNo() {
        return platformNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.platForm_No
     *
     * @param platformNo the value for alipay_account_order.platForm_No
     *
     * @mbg.generated
     */
    public void setPlatformNo(String platformNo) {
        this.platformNo = platformNo == null ? null : platformNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.new_sys_subject_id
     *
     * @return the value of alipay_account_order.new_sys_subject_id
     *
     * @mbg.generated
     */
    public Long getNewSysSubjectId() {
        return newSysSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.new_sys_subject_id
     *
     * @param newSysSubjectId the value for alipay_account_order.new_sys_subject_id
     *
     * @mbg.generated
     */
    public void setNewSysSubjectId(Long newSysSubjectId) {
        this.newSysSubjectId = newSysSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.new_Sys_Subject_Name
     *
     * @return the value of alipay_account_order.new_Sys_Subject_Name
     *
     * @mbg.generated
     */
    public String getNewSysSubjectName() {
        return newSysSubjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.new_Sys_Subject_Name
     *
     * @param newSysSubjectName the value for alipay_account_order.new_Sys_Subject_Name
     *
     * @mbg.generated
     */
    public void setNewSysSubjectName(String newSysSubjectName) {
        this.newSysSubjectName = newSysSubjectName == null ? null : newSysSubjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.new_Type
     *
     * @return the value of alipay_account_order.new_Type
     *
     * @mbg.generated
     */
    public Integer getNewType() {
        return newType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.new_Type
     *
     * @param newType the value for alipay_account_order.new_Type
     *
     * @mbg.generated
     */
    public void setNewType(Integer newType) {
        this.newType = newType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.is_Sign
     *
     * @return the value of alipay_account_order.is_Sign
     *
     * @mbg.generated
     */
    public Integer getIsSign() {
        return isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.is_Sign
     *
     * @param isSign the value for alipay_account_order.is_Sign
     *
     * @mbg.generated
     */
    public void setIsSign(Integer isSign) {
        this.isSign = isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.operator
     *
     * @return the value of alipay_account_order.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.operator
     *
     * @param operator the value for alipay_account_order.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.sign_Time
     *
     * @return the value of alipay_account_order.sign_Time
     *
     * @mbg.generated
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.sign_Time
     *
     * @param signTime the value for alipay_account_order.sign_Time
     *
     * @mbg.generated
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.new_platform_subject_id
     *
     * @return the value of alipay_account_order.new_platform_subject_id
     *
     * @mbg.generated
     */
    public Long getNewPlatformSubjectId() {
        return newPlatformSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.new_platform_subject_id
     *
     * @param newPlatformSubjectId the value for alipay_account_order.new_platform_subject_id
     *
     * @mbg.generated
     */
    public void setNewPlatformSubjectId(Long newPlatformSubjectId) {
        this.newPlatformSubjectId = newPlatformSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.new_Platform_Subject_Name
     *
     * @return the value of alipay_account_order.new_Platform_Subject_Name
     *
     * @mbg.generated
     */
    public String getNewPlatformSubjectName() {
        return newPlatformSubjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.new_Platform_Subject_Name
     *
     * @param newPlatformSubjectName the value for alipay_account_order.new_Platform_Subject_Name
     *
     * @mbg.generated
     */
    public void setNewPlatformSubjectName(String newPlatformSubjectName) {
        this.newPlatformSubjectName = newPlatformSubjectName == null ? null : newPlatformSubjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.is_Exception
     *
     * @return the value of alipay_account_order.is_Exception
     *
     * @mbg.generated
     */
    public Integer getIsException() {
        return isException;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.is_Exception
     *
     * @param isException the value for alipay_account_order.is_Exception
     *
     * @mbg.generated
     */
    public void setIsException(Integer isException) {
        this.isException = isException;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.return_id
     *
     * @return the value of alipay_account_order.return_id
     *
     * @mbg.generated
     */
    public String getReturnId() {
        return returnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.return_id
     *
     * @param returnId the value for alipay_account_order.return_id
     *
     * @mbg.generated
     */
    public void setReturnId(String returnId) {
        this.returnId = returnId == null ? null : returnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.exception_Msg
     *
     * @return the value of alipay_account_order.exception_Msg
     *
     * @mbg.generated
     */
    public String getExceptionMsg() {
        return exceptionMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.exception_Msg
     *
     * @param exceptionMsg the value for alipay_account_order.exception_Msg
     *
     * @mbg.generated
     */
    public void setExceptionMsg(String exceptionMsg) {
        this.exceptionMsg = exceptionMsg == null ? null : exceptionMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.fenxiao_id
     *
     * @return the value of alipay_account_order.fenxiao_id
     *
     * @mbg.generated
     */
    public Long getFenxiaoId() {
        return fenxiaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.fenxiao_id
     *
     * @param fenxiaoId the value for alipay_account_order.fenxiao_id
     *
     * @mbg.generated
     */
    public void setFenxiaoId(Long fenxiaoId) {
        this.fenxiaoId = fenxiaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.debtor_Code
     *
     * @return the value of alipay_account_order.debtor_Code
     *
     * @mbg.generated
     */
    public String getDebtorCode() {
        return debtorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.debtor_Code
     *
     * @param debtorCode the value for alipay_account_order.debtor_Code
     *
     * @mbg.generated
     */
    public void setDebtorCode(String debtorCode) {
        this.debtorCode = debtorCode == null ? null : debtorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.debtor_Subject
     *
     * @return the value of alipay_account_order.debtor_Subject
     *
     * @mbg.generated
     */
    public String getDebtorSubject() {
        return debtorSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.debtor_Subject
     *
     * @param debtorSubject the value for alipay_account_order.debtor_Subject
     *
     * @mbg.generated
     */
    public void setDebtorSubject(String debtorSubject) {
        this.debtorSubject = debtorSubject == null ? null : debtorSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.debtor_XNEGP
     *
     * @return the value of alipay_account_order.debtor_XNEGP
     *
     * @mbg.generated
     */
    public String getDebtorXnegp() {
        return debtorXnegp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.debtor_XNEGP
     *
     * @param debtorXnegp the value for alipay_account_order.debtor_XNEGP
     *
     * @mbg.generated
     */
    public void setDebtorXnegp(String debtorXnegp) {
        this.debtorXnegp = debtorXnegp == null ? null : debtorXnegp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.debtor_Acc_Type
     *
     * @return the value of alipay_account_order.debtor_Acc_Type
     *
     * @mbg.generated
     */
    public String getDebtorAccType() {
        return debtorAccType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.debtor_Acc_Type
     *
     * @param debtorAccType the value for alipay_account_order.debtor_Acc_Type
     *
     * @mbg.generated
     */
    public void setDebtorAccType(String debtorAccType) {
        this.debtorAccType = debtorAccType == null ? null : debtorAccType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.debtor_Cash_Flow_Code
     *
     * @return the value of alipay_account_order.debtor_Cash_Flow_Code
     *
     * @mbg.generated
     */
    public String getDebtorCashFlowCode() {
        return debtorCashFlowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.debtor_Cash_Flow_Code
     *
     * @param debtorCashFlowCode the value for alipay_account_order.debtor_Cash_Flow_Code
     *
     * @mbg.generated
     */
    public void setDebtorCashFlowCode(String debtorCashFlowCode) {
        this.debtorCashFlowCode = debtorCashFlowCode == null ? null : debtorCashFlowCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.credit_Code
     *
     * @return the value of alipay_account_order.credit_Code
     *
     * @mbg.generated
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.credit_Code
     *
     * @param creditCode the value for alipay_account_order.credit_Code
     *
     * @mbg.generated
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.credit_Subject
     *
     * @return the value of alipay_account_order.credit_Subject
     *
     * @mbg.generated
     */
    public String getCreditSubject() {
        return creditSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.credit_Subject
     *
     * @param creditSubject the value for alipay_account_order.credit_Subject
     *
     * @mbg.generated
     */
    public void setCreditSubject(String creditSubject) {
        this.creditSubject = creditSubject == null ? null : creditSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.credit_XNEGP
     *
     * @return the value of alipay_account_order.credit_XNEGP
     *
     * @mbg.generated
     */
    public String getCreditXnegp() {
        return creditXnegp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.credit_XNEGP
     *
     * @param creditXnegp the value for alipay_account_order.credit_XNEGP
     *
     * @mbg.generated
     */
    public void setCreditXnegp(String creditXnegp) {
        this.creditXnegp = creditXnegp == null ? null : creditXnegp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.credit_Acc_Type
     *
     * @return the value of alipay_account_order.credit_Acc_Type
     *
     * @mbg.generated
     */
    public String getCreditAccType() {
        return creditAccType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.credit_Acc_Type
     *
     * @param creditAccType the value for alipay_account_order.credit_Acc_Type
     *
     * @mbg.generated
     */
    public void setCreditAccType(String creditAccType) {
        this.creditAccType = creditAccType == null ? null : creditAccType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.credit_Cash_Flow_Code
     *
     * @return the value of alipay_account_order.credit_Cash_Flow_Code
     *
     * @mbg.generated
     */
    public String getCreditCashFlowCode() {
        return creditCashFlowCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.credit_Cash_Flow_Code
     *
     * @param creditCashFlowCode the value for alipay_account_order.credit_Cash_Flow_Code
     *
     * @mbg.generated
     */
    public void setCreditCashFlowCode(String creditCashFlowCode) {
        this.creditCashFlowCode = creditCashFlowCode == null ? null : creditCashFlowCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.is_reconciled
     *
     * @return the value of alipay_account_order.is_reconciled
     *
     * @mbg.generated
     */
    public Boolean getIsReconciled() {
        return isReconciled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.is_reconciled
     *
     * @param isReconciled the value for alipay_account_order.is_reconciled
     *
     * @mbg.generated
     */
    public void setIsReconciled(Boolean isReconciled) {
        this.isReconciled = isReconciled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.reconcile_time
     *
     * @return the value of alipay_account_order.reconcile_time
     *
     * @mbg.generated
     */
    public Date getReconcileTime() {
        return reconcileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.reconcile_time
     *
     * @param reconcileTime the value for alipay_account_order.reconcile_time
     *
     * @mbg.generated
     */
    public void setReconcileTime(Date reconcileTime) {
        this.reconcileTime = reconcileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.ims_Push_Msg
     *
     * @return the value of alipay_account_order.ims_Push_Msg
     *
     * @mbg.generated
     */
    public String getImsPushMsg() {
        return imsPushMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.ims_Push_Msg
     *
     * @param imsPushMsg the value for alipay_account_order.ims_Push_Msg
     *
     * @mbg.generated
     */
    public void setImsPushMsg(String imsPushMsg) {
        this.imsPushMsg = imsPushMsg == null ? null : imsPushMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.ims_Push_Time
     *
     * @return the value of alipay_account_order.ims_Push_Time
     *
     * @mbg.generated
     */
    public Date getImsPushTime() {
        return imsPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.ims_Push_Time
     *
     * @param imsPushTime the value for alipay_account_order.ims_Push_Time
     *
     * @mbg.generated
     */
    public void setImsPushTime(Date imsPushTime) {
        this.imsPushTime = imsPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.cancel
     *
     * @return the value of alipay_account_order.cancel
     *
     * @mbg.generated
     */
    public Boolean getCancel() {
        return cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.cancel
     *
     * @param cancel the value for alipay_account_order.cancel
     *
     * @mbg.generated
     */
    public void setCancel(Boolean cancel) {
        this.cancel = cancel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.cancel_operator
     *
     * @return the value of alipay_account_order.cancel_operator
     *
     * @mbg.generated
     */
    public String getCancelOperator() {
        return cancelOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.cancel_operator
     *
     * @param cancelOperator the value for alipay_account_order.cancel_operator
     *
     * @mbg.generated
     */
    public void setCancelOperator(String cancelOperator) {
        this.cancelOperator = cancelOperator == null ? null : cancelOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.cancel_date
     *
     * @return the value of alipay_account_order.cancel_date
     *
     * @mbg.generated
     */
    public Date getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.cancel_date
     *
     * @param cancelDate the value for alipay_account_order.cancel_date
     *
     * @mbg.generated
     */
    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.subject_convert
     *
     * @return the value of alipay_account_order.subject_convert
     *
     * @mbg.generated
     */
    public Integer getSubjectConvert() {
        return subjectConvert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.subject_convert
     *
     * @param subjectConvert the value for alipay_account_order.subject_convert
     *
     * @mbg.generated
     */
    public void setSubjectConvert(Integer subjectConvert) {
        this.subjectConvert = subjectConvert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.plus_or_minus
     *
     * @return the value of alipay_account_order.plus_or_minus
     *
     * @mbg.generated
     */
    public Integer getPlusOrMinus() {
        return plusOrMinus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.plus_or_minus
     *
     * @param plusOrMinus the value for alipay_account_order.plus_or_minus
     *
     * @mbg.generated
     */
    public void setPlusOrMinus(Integer plusOrMinus) {
        this.plusOrMinus = plusOrMinus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.test_field
     *
     * @return the value of alipay_account_order.test_field
     *
     * @mbg.generated
     */
    public String getTestField() {
        return testField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.test_field
     *
     * @param testField the value for alipay_account_order.test_field
     *
     * @mbg.generated
     */
    public void setTestField(String testField) {
        this.testField = testField == null ? null : testField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.sapcolsechangtime
     *
     * @return the value of alipay_account_order.sapcolsechangtime
     *
     * @mbg.generated
     */
    public Date getSapcolsechangtime() {
        return sapcolsechangtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.sapcolsechangtime
     *
     * @param sapcolsechangtime the value for alipay_account_order.sapcolsechangtime
     *
     * @mbg.generated
     */
    public void setSapcolsechangtime(Date sapcolsechangtime) {
        this.sapcolsechangtime = sapcolsechangtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.is_hz
     *
     * @return the value of alipay_account_order.is_hz
     *
     * @mbg.generated
     */
    public Integer getIsHz() {
        return isHz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.is_hz
     *
     * @param isHz the value for alipay_account_order.is_hz
     *
     * @mbg.generated
     */
    public void setIsHz(Integer isHz) {
        this.isHz = isHz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_account_order.memo
     *
     * @return the value of alipay_account_order.memo
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_account_order.memo
     *
     * @param memo the value for alipay_account_order.memo
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}