package com.dao.warning;

import com.entity.warning.WarningOperLog;

public interface WarningOperLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_oper_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_oper_log
     *
     * @mbg.generated
     */
    int insert(WarningOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_oper_log
     *
     * @mbg.generated
     */
    int insertSelective(WarningOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_oper_log
     *
     * @mbg.generated
     */
    WarningOperLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_oper_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WarningOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_oper_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WarningOperLog record);
}