package com.entity.warning;

import java.util.Date;

public class WarningOperLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_oper_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_oper_log.operUser
     *
     * @mbg.generated
     */
    private String operuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_oper_log.operTypeName
     *
     * @mbg.generated
     */
    private String opertypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_oper_log.platfromCode
     *
     * @mbg.generated
     */
    private String platfromcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_oper_log.warnCode
     *
     * @mbg.generated
     */
    private Integer warnHeaderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_oper_log.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_oper_log.attribuate1
     *
     * @mbg.generated
     */
    private String attribuate1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_oper_log.attribuate2
     *
     * @mbg.generated
     */
    private String attribuate2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_oper_log.attribuate3
     *
     * @mbg.generated
     */
    private String attribuate3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_oper_log.id
     *
     * @return the value of warning_oper_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_oper_log.id
     *
     * @param id the value for warning_oper_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_oper_log.operUser
     *
     * @return the value of warning_oper_log.operUser
     *
     * @mbg.generated
     */
    public String getOperuser() {
        return operuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_oper_log.operUser
     *
     * @param operuser the value for warning_oper_log.operUser
     *
     * @mbg.generated
     */
    public void setOperuser(String operuser) {
        this.operuser = operuser == null ? null : operuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_oper_log.operTypeName
     *
     * @return the value of warning_oper_log.operTypeName
     *
     * @mbg.generated
     */
    public String getOpertypename() {
        return opertypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_oper_log.operTypeName
     *
     * @param opertypename the value for warning_oper_log.operTypeName
     *
     * @mbg.generated
     */
    public void setOpertypename(String opertypename) {
        this.opertypename = opertypename == null ? null : opertypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_oper_log.platfromCode
     *
     * @return the value of warning_oper_log.platfromCode
     *
     * @mbg.generated
     */
    public String getPlatfromcode() {
        return platfromcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_oper_log.platfromCode
     *
     * @param platfromcode the value for warning_oper_log.platfromCode
     *
     * @mbg.generated
     */
    public void setPlatfromcode(String platfromcode) {
        this.platfromcode = platfromcode == null ? null : platfromcode.trim();
    }

    public Integer getWarnHeaderId() {
        return warnHeaderId;
    }

    public void setWarnHeaderId(Integer warnHeaderId) {
        this.warnHeaderId = warnHeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_oper_log.createTime
     *
     * @return the value of warning_oper_log.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_oper_log.createTime
     *
     * @param createtime the value for warning_oper_log.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_oper_log.attribuate1
     *
     * @return the value of warning_oper_log.attribuate1
     *
     * @mbg.generated
     */
    public String getAttribuate1() {
        return attribuate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_oper_log.attribuate1
     *
     * @param attribuate1 the value for warning_oper_log.attribuate1
     *
     * @mbg.generated
     */
    public void setAttribuate1(String attribuate1) {
        this.attribuate1 = attribuate1 == null ? null : attribuate1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_oper_log.attribuate2
     *
     * @return the value of warning_oper_log.attribuate2
     *
     * @mbg.generated
     */
    public String getAttribuate2() {
        return attribuate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_oper_log.attribuate2
     *
     * @param attribuate2 the value for warning_oper_log.attribuate2
     *
     * @mbg.generated
     */
    public void setAttribuate2(String attribuate2) {
        this.attribuate2 = attribuate2 == null ? null : attribuate2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_oper_log.attribuate3
     *
     * @return the value of warning_oper_log.attribuate3
     *
     * @mbg.generated
     */
    public String getAttribuate3() {
        return attribuate3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_oper_log.attribuate3
     *
     * @param attribuate3 the value for warning_oper_log.attribuate3
     *
     * @mbg.generated
     */
    public void setAttribuate3(String attribuate3) {
        this.attribuate3 = attribuate3 == null ? null : attribuate3.trim();
    }
}